### ISSUE TITLE
[BUG] configuration files ignored?

### ISSUE THREAD

**Issue by mathause** [s-weigand/flake8-nb#174]
**Describe the bug**
I have a setup.cfg file in my project that seems to be ignored by flake8_nb (but not by flake8).

**To Reproduce**

Create a `setup.cfg` file containing

```
[flake8]
ignore=
    E501 # line too long 
```

- run flake8 on a `*.py` file with a line that is too long
- fun flake8_nb on a `*.ipynb` file with a line that is too long

**Expected behavior**
No E501 error.

**Desktop (please complete the following information):**

- OS: linux
```
flake8                    3.8.4                      py_0    conda-forge
flake8-nb                 0.3.1              pyhd8ed1ab_0    conda-forge
```

**Additional context**

**Comment by s-weigand** [comment]
You need to change your config
```diff
-[flake8]
+[flake8_nb]
```
Since you are the [second person raising this issue in a short time](https://github.com/s-weigand/flake8-nb/issues/172), I guess I should put the configuration more prominently in the readme.

**Comment by mathause** [comment]
Ah well one should read the docs before posting an issue - thanks.
