### ISSUE TITLE
flake8-nb is reading `.flake8_nb` instead of reading `.flake8` 

### ISSUE THREAD

**Issue by jtmiclat** [s-weigand/flake8-nb#25]
-   flake8-nb version: 0.1.4 . 
-   Python version: 3.7.7
-   Operating System: Ubuntu 18.04 LTS

### Description
HI thanks for a cool package!  I was looking at the docs it mentions to configure `flake8_nb` you can use `.flake8` https://github.com/s-weigand/flake8-nb/blob/master/docs/usage.rst. After experimenting and debugging it seems like it will not read  `.flake8` but instead reads `.flake8_nb` 

### What I Did

Generate a notebook with more than 79 char lines.
Create a `.flake8` containing the following
```
[flake8_nb]
ignore = E501
```
Run the flake8-nb command 
```
flake8_nb notebook.ipynb
```
This generates the following warnings
```
notebook1ipynb#In[1]:1:80: E501 line too long (84 > 79 characters)
```
Move `.flake8` to `.flake8_nb` to fix.

Not 100% if this a docs issue or an actual bug

**Comment by s-weigand** [comment]
Thats an issue with the docs, thanks for reporting, I fixed it 😄

**Comment by s-weigand** [comment]
@all-contributors please add @jtmiclat for bug
